[package]
name = "xlsx2csv"
version = "0.1.0"
authors = ["Huo Linhe <linhehuo@gmail.com>"]
description = "Excel XLSX to CSV converter"

[dependencies]
calamine = "0.11.7"
csv = "1.0.0-beta.3"
clap = "2.25.0"
pbr = "1.0.0"
